SELECT * FROM jobaaj.customers;
SELECT count(*) FROM jobaaj.customers;
# BASIC PROBLEMS
# 1. List all unique cities where customers are located.
SELECT DISTINCT customer_city
FROM jobaaj.customers;
# 2. Count the number of orders placed in 2017.
SELECT COUNT(*) AS total_orders_2017
FROM jobaaj.orders
WHERE YEAR(order_purchase_timestamp) = 2017;
# 3. Find the total sales per category.
SELECT 
    p. `product category` AS category,
    SUM(oi.price) AS total_sales
FROM jobaaj.order_items oi
JOIN jobaaj.products p 
    ON oi.product_id = p.product_id
JOIN jobaaj.orders o 
    ON oi.order_id = o.order_id
GROUP BY p. `product category`
ORDER BY total_sales DESC;
# 4. Calculate the percentage of orders that were paid in installments. 
SELECT 
    ROUND(
        (COUNT(DISTINCT CASE WHEN p.payment_installments > 1 THEN p.order_id END) 
         / COUNT(DISTINCT o.order_id)) * 100, 2
    ) AS pct_orders_installments
FROM jobaaj.orders o
JOIN jobaaj.payments p 
    ON o.order_id = p.order_id;
# 5. Count the number of customers from each state.
SELECT 
    customer_state,
    COUNT(*) AS total_customers
FROM jobaaj.customers
GROUP BY customer_state
ORDER BY total_customers DESC;
# INTERMEDIATE PROBLEMS
# 1. Calculate the number of orders per month in 2018.
SELECT 
    DATE_FORMAT(order_purchase_timestamp, '%Y-%m') AS order_month,
    COUNT(*) AS total_orders
FROM jobaaj.orders
WHERE YEAR(order_purchase_timestamp) = 2018
GROUP BY DATE_FORMAT(order_purchase_timestamp, '%Y-%m')
ORDER BY order_month;
# 2. Find the average number of products per order, grouped by customer city. 
SELECT 
    c.customer_city,
    ROUND(AVG(order_counts.num_products), 2) AS avg_products_per_order
FROM (
    SELECT 
        o.order_id,
        COUNT(oi.product_id) AS num_products,
        o.customer_id
    FROM jobaaj.order_items oi
    JOIN jobaaj.orders o 
        ON oi.order_id = o.order_id
    GROUP BY o.order_id, o.customer_id
) AS order_counts
JOIN jobaaj.customers c 
    ON order_counts.customer_id = c.customer_id
GROUP BY c.customer_city
ORDER BY avg_products_per_order DESC;
# 3. Calculate the percentage of total revenue contributed by each product category. 
SELECT 
    p.`product category` AS category,
    ROUND(
        (SUM(oi.price + oi.freight_value) / 
         (SELECT SUM(price + freight_value) FROM jobaaj.order_items)) * 100, 2
    ) AS pct_revenue
FROM jobaaj.order_items oi
JOIN jobaaj.products p 
    ON oi.product_id = p.product_id
GROUP BY p.`product category`
ORDER BY pct_revenue DESC;
# 4. Identify the correlation between product price and the number of times a product has been purchased.
SELECT 
    product_id,
    COUNT(*) AS purchase_count,
    AVG(price) AS avg_price
FROM jobaaj.order_items
GROUP BY product_id
HAVING purchase_count > 1;
# 5. Calculate the total revenue generated by each seller, and rank them by revenue.
SELECT 
    seller_id,
    SUM(price + freight_value) AS total_revenue,
    RANK() OVER (ORDER BY SUM(price + freight_value) DESC) AS revenue_rank
FROM jobaaj.order_items
GROUP BY seller_id
ORDER BY total_revenue DESC;
# ADVANCED PROBLEMS
# 1. Calculate the moving average of order values for each customer over their order history.
WITH order_values AS (
    SELECT 
        o.order_id,
        o.customer_id,
        o.order_purchase_timestamp,
        SUM(oi.price + oi.freight_value) AS order_value
    FROM jobaaj.orders o
    JOIN jobaaj.order_items oi 
        ON o.order_id = oi.order_id
    GROUP BY o.order_id, o.customer_id, o.order_purchase_timestamp
)
SELECT
    customer_id,
    order_id,
    order_purchase_timestamp,
    order_value,
    ROUND(
        AVG(order_value) OVER (
            PARTITION BY customer_id 
            ORDER BY order_purchase_timestamp
            ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
        ), 2
    ) AS moving_avg_order_value
FROM order_values
ORDER BY customer_id, order_purchase_timestamp;
# 2. Calculate the cumulative sales per month for each year.
WITH monthly_sales AS (
    SELECT 
        YEAR(o.order_purchase_timestamp) AS order_year,
        MONTH(o.order_purchase_timestamp) AS order_month,
        SUM(oi.price + oi.freight_value) AS monthly_revenue
    FROM jobaaj.orders o
    JOIN jobaaj.order_items oi 
        ON o.order_id = oi.order_id
    GROUP BY YEAR(o.order_purchase_timestamp), MONTH(o.order_purchase_timestamp)
)
SELECT 
    order_year,
    order_month,
    monthly_revenue,
    ROUND(
        SUM(monthly_revenue) OVER (
            PARTITION BY order_year 
            ORDER BY order_month
        ), 2
    ) AS cumulative_revenue
FROM monthly_sales
ORDER BY order_year, order_month;
# 3. Calculate the year-over-year growth rate of total sales.
 WITH yearly_sales AS (
    SELECT 
        YEAR(o.order_purchase_timestamp) AS order_year,
        SUM(oi.price + oi.freight_value) AS total_sales
    FROM jobaaj.orders o
    JOIN jobaaj.order_items oi 
        ON o.order_id = oi.order_id
    GROUP BY YEAR(o.order_purchase_timestamp)
)
SELECT
    order_year,
    total_sales,
    ROUND(
        ((total_sales - LAG(total_sales) OVER (ORDER BY order_year)) 
          / LAG(total_sales) OVER (ORDER BY order_year)) * 100, 2
    ) AS yoy_growth_rate
FROM yearly_sales
ORDER BY order_year;
# 4. Calculate the retention rate of customers, defined as the percentage of customers 
# who make another purchase within 6 months of their first purchase. 
WITH first_purchase AS (
    SELECT 
        customer_id,
        MIN(order_purchase_timestamp) AS first_order_date
    FROM jobaaj.orders
    GROUP BY customer_id
),
next_purchase AS (
    SELECT 
        o.customer_id,
        MIN(o.order_purchase_timestamp) AS second_order_date
    FROM jobaaj.orders o
    JOIN first_purchase fp 
        ON o.customer_id = fp.customer_id
       AND o.order_purchase_timestamp > fp.first_order_date
    GROUP BY o.customer_id
)
SELECT 
    ROUND(
        (COUNT(CASE WHEN TIMESTAMPDIFF(MONTH, fp.first_order_date, np.second_order_date) <= 6 THEN 1 END) 
        / COUNT(fp.customer_id)) * 100, 2
    ) AS retention_rate_pct
FROM first_purchase fp
LEFT JOIN next_purchase np 
    ON fp.customer_id = np.customer_id;
# 5. Identify the top 3 customers who spent the most money in each year.
WITH customer_yearly_spending AS (
    SELECT 
        YEAR(o.order_purchase_timestamp) AS order_year,
        o.customer_id,
        SUM(oi.price + oi.freight_value) AS total_spent
    FROM jobaaj.orders o
    JOIN jobaaj.order_items oi 
        ON o.order_id = oi.order_id
    GROUP BY YEAR(o.order_purchase_timestamp), o.customer_id
),
ranked_customers AS (
    SELECT 
        order_year,
        customer_id,
        total_spent,
        RANK() OVER (PARTITION BY order_year ORDER BY total_spent DESC) AS spending_rank
    FROM customer_yearly_spending
)
SELECT 
    order_year,
    customer_id,
    total_spent,
    spending_rank
FROM ranked_customers
WHERE spending_rank <= 3
ORDER BY order_year, spending_rank;